// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_NwqMlkWCIwQfWVFF6OvdJtZCzPP1bA',
    appId: '1:310834065683:web:e85143e36a586dd563aae6',
    messagingSenderId: '310834065683',
    projectId: 'medicareapp-56fa1',
    authDomain: 'medicareapp-56fa1.firebaseapp.com',
    databaseURL: 'https://medicareapp-56fa1-default-rtdb.firebaseio.com',
    storageBucket: 'medicareapp-56fa1.firebasestorage.app',
    measurementId: 'G-79W3ME0R3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNSqZu-pvd0TWACJUPkq-7yjYkt9arzA',
    appId: '1:310834065683:android:27d870e7dd1571a763aae6',
    messagingSenderId: '310834065683',
    projectId: 'medicareapp-56fa1',
    databaseURL: 'https://medicareapp-56fa1-default-rtdb.firebaseio.com',
    storageBucket: 'medicareapp-56fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJj6Nxj6fQK26v-RigcWGm1FYiaQ0W5fk',
    appId: '1:310834065683:ios:d1cb38382220369763aae6',
    messagingSenderId: '310834065683',
    projectId: 'medicareapp-56fa1',
    databaseURL: 'https://medicareapp-56fa1-default-rtdb.firebaseio.com',
    storageBucket: 'medicareapp-56fa1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJj6Nxj6fQK26v-RigcWGm1FYiaQ0W5fk',
    appId: '1:310834065683:ios:d1cb38382220369763aae6',
    messagingSenderId: '310834065683',
    projectId: 'medicareapp-56fa1',
    databaseURL: 'https://medicareapp-56fa1-default-rtdb.firebaseio.com',
    storageBucket: 'medicareapp-56fa1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq_NwqMlkWCIwQfWVFF6OvdJtZCzPP1bA',
    appId: '1:310834065683:web:120912fead88b80263aae6',
    messagingSenderId: '310834065683',
    projectId: 'medicareapp-56fa1',
    authDomain: 'medicareapp-56fa1.firebaseapp.com',
    databaseURL: 'https://medicareapp-56fa1-default-rtdb.firebaseio.com',
    storageBucket: 'medicareapp-56fa1.firebasestorage.app',
    measurementId: 'G-6C9S8MWFJ0',
  );
}
